// Generated by CoffeeScript 1.6.3
$(function() {
  /*
    EventHandler
  */

  var beforeRange, cellSelect, changeDayMode, changeMonthMode, changeWeekMode, displayRange, drowCalendar, moveToday, nextRange, schedule;
  $('#today').on('click', function() {
    return moveToday();
  });
  $('#before').on('click', function() {
    return beforeRange();
  });
  $('#next').on('click', function() {
    return nextRange();
  });
  $('#monthMode').on('click', function() {
    return changeMonthMode();
  });
  $('#weekMode').on('click', function() {
    return changeWeekMode();
  });
  $('#dayMode').on('click', function() {
    return changeDayMode();
  });
  $('#calendar').on('click', 'td', function(event) {
    return cellSelect(event);
  });
  /*
    Model
  */

  schedule = {
    day: Date,
    subject: String,
    detail: String
  };
  displayRange = {
    today: new ponDate(),
    start: new ponDate(),
    mode: 'month',
    range: 6,
    moveRange: function(val) {
      if (val == null) {
        val = null;
      }
      switch (this.mode) {
        case 'day':
          if (val) {
            this.today.addDay(val);
          }
          return this.start.copy(this.today);
        case 'week':
          if (val) {
            this.today.addWeek(val);
          }
          this.start.copy(this.today);
          this.start.addDay(-this.start.getWeekDay());
          return this.range = 1;
        case 'month':
          if (val) {
            this.today.addMonth(val);
          }
          this.start.copy(this.today);
          this.start.setDay(1);
          this.start.addDay(this.start.getWeekDay() === 0 ? -7 : -this.start.getWeekDay());
          return this.range = 6;
      }
    },
    changeMode: function(mode) {
      this.mode = mode;
      return this.moveRange();
    },
    moveToday: function() {
      this.today = new ponDate();
      return this.moveRange();
    }
  };
  /*
    Controller
  */

  moveToday = function() {
    displayRange.moveToday();
    return drowCalendar();
  };
  beforeRange = function() {
    displayRange.moveRange(-1);
    return drowCalendar();
  };
  nextRange = function() {
    displayRange.moveRange(1);
    return drowCalendar();
  };
  changeMonthMode = function() {
    displayRange.changeMode('month');
    displayRange.moveRange();
    return drowCalendar();
  };
  changeWeekMode = function() {
    displayRange.changeMode('week');
    displayRange.moveRange();
    return drowCalendar();
  };
  changeDayMode = function() {
    displayRange.changeMode('day');
    return drowCalendar();
  };
  cellSelect = function(event) {
    var tmpArray;
    $('.selectday').removeClass('selectday');
    $(event.currentTarget).addClass('selectday');
    tmpArray = $(event.currentTarget).attr('id').split('-');
    tmpArray[0] = Number(tmpArray[0]);
    tmpArray[1] = Number(tmpArray[1]);
    tmpArray[2] = Number(tmpArray[2]);
    displayRange.today.setDate(tmpArray[0], tmpArray[1], tmpArray[2]);
    return displayRange.moveRange();
  };
  /*
    View
  */

  drowCalendar = function() {
    var dispDate, tableTxt, weeks, _i, _j;
    $('#calendar').empty();
    tableTxt = [];
    dispDate = new ponDate();
    dispDate.copy(displayRange.start);
    if (displayRange.mode === 'day') {
      tableTxt.push('<table class="day"><tbody><tr><th>', dispDate.getWeekString(), '</th></tr><tr><td id="', displayRange.today.getDate().replace(/\//g, '-'), '"><p>', dispDate.getDay(), '</p></td></tr></tbody></table>');
      $('#thisRange').text(displayRange.today.getDate());
    } else {
      tableTxt.push('<table class="', displayRange.mode, '"><tbody><tr><th>日</th><th>月</th><th>火</th><th>水</th><th>木</th><th>金</th><th>土</th></tr>');
      weeks = displayRange.range;
      for (_i = 1; 1 <= weeks ? _i <= weeks : _i >= weeks; 1 <= weeks ? _i++ : _i--) {
        tableTxt.push('<tr>');
        for (_j = 1; _j <= 7; _j++) {
          tableTxt.push('<td id="', dispDate.getDate().replace(/\//g, '-'), '"><p>', dispDate.getDay(), '</p></td>');
          dispDate.addDay(1);
        }
        tableTxt.push('</tr>');
      }
      tableTxt.push('</tbody></table>');
      $('#thisRange').text(displayRange.today.getDate());
    }
    $('#calendar').append(tableTxt.join(''));
    $('tr').children('td[id^="' + displayRange.today.getYear() + '-' + displayRange.today.getMonth() + '"]').children('p').css('color', '#000');
    return $('#' + dispDate.getDate().replace(/\//g, '-')).addClass('selectday');
  };
  displayRange.moveToday();
  return drowCalendar();
});
