// Generated by CoffeeScript 1.6.3
$(function() {
  /*
    EventHandler
  */

  var displayRange, schedule;
  $('#today').on('click', function() {
    return displayRange.moveToday();
  });
  $('#before').on('click', function() {
    return displayRange.moveRange(-1);
  });
  $('#next').on('click', function() {
    return displayRange.moveRange(1);
  });
  $('#monthMode').on('click', function() {
    return displayRange.changeMode('month');
  });
  $('#weekMode').on('click', function() {
    return displayRange.changeMode('week');
  });
  $('#dayMode').on('click', function() {
    return displayRange.changeMode('day');
  });
  /*
    Model
  */

  schedule = {
    day: Date,
    subject: String,
    detail: String
  };
  return displayRange = {
    today: new Date(),
    start: {},
    end: {},
    days: Number,
    mode: 'month',
    copyDate: function(day) {
      return new Date(day.getFullYear(), day.getMonth(), day.getDate());
    },
    moveToday: function() {
      this.today = new Date();
      return this.moveRange(0);
    },
    moveRange: function(vol) {
      this.start = this.copyDate(this.today);
      switch (this.mode) {
        case 'day':
          this.start.setDate(this.start.getDate() + vol);
          this.today.setDate(this.today.getDate() + vol);
          $('#calendar').text(this.start.toLocaleDateString());
          break;
        case 'week':
          this.start.setDate(this.start.getDate() + vol * 7);
          this.start.setDate(this.start.getDate() - this.start.getDay());
          this.end = this.copyDate(this.start);
          this.end.setDate(this.end.getDate() + 6);
          this.today.setDate(this.today.getDate() + vol * 7);
          $('#calendar').text(this.start.toLocaleDateString() + ' - ' + this.end.toLocaleDateString());
          break;
        case 'month':
          this.start.setMonth(this.start.getMonth() + vol);
          this.start.setDate(1);
          this.start.setDate(1 - this.start.getDay());
          this.today.setMonth(this.today.getMonth() + vol);
          this.end = this.copyDate(this.start);
          this.end.setDate(this.end.getDate() + 41);
          $('#calendar').text(this.start.toLocaleDateString() + ' - ' + this.end.toLocaleDateString());
          break;
      }
      return $('#thisRange').text(this.today.toLocaleDateString());
    },
    changeMode: function(mode) {
      this.mode = mode;
      return this.moveRange(0);
    }
  };
  /*
    View
  */

});
