// Generated by CoffeeScript 1.6.3
$(function() {
  /*
    EventHandler
  */

  var calendar, changeMode, changeStartDay, drowCalendar, goBack, goNext, goToday, selectDate;
  $('#goToday').on('click', function() {
    return goToday();
  });
  $('#goBack').on('click', function() {
    return goBack();
  });
  $('#goNext').on('click', function() {
    return goNext();
  });
  $('#changeModeMonth').on('click', function() {
    return changeMode('month');
  });
  $('#changeModeWeek').on('click', function() {
    return changeMode('week');
  });
  $('#changeModeDay').on('click', function() {
    return changeMode('day');
  });
  $('#changeStartDay').on('change', function() {
    return changeStartDay();
  });
  $('#calendar').on('click', 'td', function(event) {
    return selectDate(event);
  });
  /*
    Model
  */

  calendar = {
    day: new ponDate(),
    range: {
      month: [6, 7],
      week: [1, 7],
      day: [1, 1]
    },
    mode: 'month',
    start: 0,
    today: function() {
      return this.day = new ponDate();
    },
    moveDay: function(width) {
      if (width == null) {
        width = null;
      }
      if (!width) {
        return;
      }
      switch (this.mode) {
        case 'month':
          return this.day.addMonth(width);
        case 'week':
          return this.day.addWeek(width);
        case 'day':
          return this.day.addDay(width);
      }
    },
    changeMode: function(mode) {
      if (this.mode !== mode) {
        return this.mode = mode;
      }
    },
    changeStartDay: function(day) {
      return this.start = day;
    }
  };
  /*
    Controller
  */

  goToday = function() {
    calendar.today();
    return drowCalendar();
  };
  goBack = function() {
    calendar.moveDay(-1);
    return drowCalendar();
  };
  goNext = function() {
    calendar.moveDay(1);
    return drowCalendar();
  };
  changeMode = function(mode) {
    calendar.changeMode(mode);
    drowCalendar();
    if (mode === 'day') {
      return $('#changeStartDay').attr('disabled', 'disabled');
    } else {
      return $('#changeStartDay').removeAttr('disabled', 'disabled');
    }
  };
  changeStartDay = function() {
    calendar.changeStartDay(Number($('#changeStartDay').children('option:selected').val()));
    return drowCalendar();
  };
  selectDate = function(event) {
    var currentDay;
    $('.selectDay').removeClass('selectDay');
    currentDay = $(event.currentTarget);
    currentDay.addClass('selectDay');
    calendar.day.setDate(currentDay.attr('id'));
    return $('#thisRange').text(calendar.day.getDate());
  };
  /*
    View
  */

  drowCalendar = function() {
    var addDay, drowDate, h, tableTxt, weekArray, _i, _j, _k, _ref, _ref1, _ref2;
    $('#calendar').empty();
    tableTxt = [];
    drowDate = new ponDate();
    drowDate.copy(calendar.day);
    if (calendar.mode === 'month') {
      drowDate.setDay(1);
      addDay = ((7 - calendar.start) % 7 + drowDate.getWeekDay()) % 7;
      if (addDay === 0) {
        addDay = 7;
      }
      drowDate.addDay(-addDay);
    } else if (calendar.mode === 'week') {
      addDay = ((7 - calendar.start) % 7 + drowDate.getWeekDay()) % 7;
      drowDate.addDay(-addDay);
    }
    tableTxt.push('<table id="', calendar.mode, '"><tbody><tr>');
    if (calendar.mode === 'day') {
      tableTxt.push('<th>', drowDate.getWeekString(), '</th></tr>');
    } else {
      weekArray = '日月火水木金土日月火水木金';
      for (h = _i = 0, _ref = calendar.range[calendar.mode][1]; 0 <= _ref ? _i < _ref : _i > _ref; h = 0 <= _ref ? ++_i : --_i) {
        tableTxt.push('<th>', weekArray[h + calendar.start], '</th>');
      }
      tableTxt.push('</tr>');
    }
    for (_j = 1, _ref1 = calendar.range[calendar.mode][0]; 1 <= _ref1 ? _j <= _ref1 : _j >= _ref1; 1 <= _ref1 ? _j++ : _j--) {
      tableTxt.push('<tr>');
      for (_k = 1, _ref2 = calendar.range[calendar.mode][1]; 1 <= _ref2 ? _k <= _ref2 : _k >= _ref2; 1 <= _ref2 ? _k++ : _k--) {
        tableTxt.push('<td id="', drowDate.getDate().replace(/\//g, '-'), drowDate.getWeekDay() === 0 ? '" class="sunday' : void 0, drowDate.getWeekDay() === 6 ? '" class="saturday' : void 0, '">', drowDate.getDay(), '</td>');
        drowDate.addDay(1);
      }
      tableTxt.push('</tr>');
    }
    tableTxt.push('</tbody></table>');
    $('#calendar').append(tableTxt.join(''));
    $('tr').children('td[id^="' + calendar.day.getYear() + '-' + calendar.day.getMonth() + '"]').css('color', '#000');
    $('#thisRange').text(calendar.day.getDate());
    return $('td[id^="' + calendar.day.getDate().replace(/\//g, '-') + '"]').addClass('selectDay');
  };
  return drowCalendar();
});
